/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as RoleRouteImport } from './routes/role'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedCarePlanRouteImport } from './routes/_authenticated/care-plan'
import { Route as AuthenticatedSharedRouteImport } from './routes/_authenticated/shared'
import { Route as AuthenticatedCaregiverIndexRouteImport } from './routes/_authenticated/caregiver.index'
import { Route as AuthenticatedCaregiverProfileRouteImport } from './routes/_authenticated/caregiver.profile'
import { Route as AuthenticatedFamilyIndexRouteImport } from './routes/_authenticated/family.index'
import { Route as AuthenticatedFamilyMatchesRouteImport } from './routes/_authenticated/family.matches'
import { Route as AuthenticatedFamilyProfileRouteImport } from './routes/_authenticated/family.profile'
import { Route as AuthenticatedFamilyRequestRouteImport } from './routes/_authenticated/family.request'
import { Route as AuthenticatedOnboardingCaregiverRouteImport } from './routes/_authenticated/onboarding.caregiver'
import { Route as AuthenticatedOnboardingFamilyRouteImport } from './routes/_authenticated/onboarding.family'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleRoute = RoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCarePlanRoute = AuthenticatedCarePlanRouteImport.update({
  id: '/care-plan',
  path: '/care-plan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSharedRoute = AuthenticatedSharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCaregiverIndexRoute =
  AuthenticatedCaregiverIndexRouteImport.update({
    id: '/caregiver/',
    path: '/caregiver/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCaregiverProfileRoute =
  AuthenticatedCaregiverProfileRouteImport.update({
    id: '/caregiver/profile',
    path: '/caregiver/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFamilyIndexRoute =
  AuthenticatedFamilyIndexRouteImport.update({
    id: '/family/',
    path: '/family/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFamilyMatchesRoute =
  AuthenticatedFamilyMatchesRouteImport.update({
    id: '/family/matches',
    path: '/family/matches',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFamilyProfileRoute =
  AuthenticatedFamilyProfileRouteImport.update({
    id: '/family/profile',
    path: '/family/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFamilyRequestRoute =
  AuthenticatedFamilyRequestRouteImport.update({
    id: '/family/request',
    path: '/family/request',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingCaregiverRoute =
  AuthenticatedOnboardingCaregiverRouteImport.update({
    id: '/onboarding/caregiver',
    path: '/onboarding/caregiver',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingFamilyRoute =
  AuthenticatedOnboardingFamilyRouteImport.update({
    id: '/onboarding/family',
    path: '/onboarding/family',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/role': typeof RoleRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/care-plan': typeof AuthenticatedCarePlanRoute
  '/shared': typeof AuthenticatedSharedRoute
  '/caregiver/profile': typeof AuthenticatedCaregiverProfileRoute
  '/family/matches': typeof AuthenticatedFamilyMatchesRoute
  '/family/profile': typeof AuthenticatedFamilyProfileRoute
  '/family/request': typeof AuthenticatedFamilyRequestRoute
  '/onboarding/caregiver': typeof AuthenticatedOnboardingCaregiverRoute
  '/onboarding/family': typeof AuthenticatedOnboardingFamilyRoute
  '/caregiver/': typeof AuthenticatedCaregiverIndexRoute
  '/family/': typeof AuthenticatedFamilyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/role': typeof RoleRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/care-plan': typeof AuthenticatedCarePlanRoute
  '/shared': typeof AuthenticatedSharedRoute
  '/caregiver/profile': typeof AuthenticatedCaregiverProfileRoute
  '/family/matches': typeof AuthenticatedFamilyMatchesRoute
  '/family/profile': typeof AuthenticatedFamilyProfileRoute
  '/family/request': typeof AuthenticatedFamilyRequestRoute
  '/onboarding/caregiver': typeof AuthenticatedOnboardingCaregiverRoute
  '/onboarding/family': typeof AuthenticatedOnboardingFamilyRoute
  '/caregiver': typeof AuthenticatedCaregiverIndexRoute
  '/family': typeof AuthenticatedFamilyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/role': typeof RoleRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/care-plan': typeof AuthenticatedCarePlanRoute
  '/_authenticated/shared': typeof AuthenticatedSharedRoute
  '/_authenticated/caregiver/profile': typeof AuthenticatedCaregiverProfileRoute
  '/_authenticated/family/matches': typeof AuthenticatedFamilyMatchesRoute
  '/_authenticated/family/profile': typeof AuthenticatedFamilyProfileRoute
  '/_authenticated/family/request': typeof AuthenticatedFamilyRequestRoute
  '/_authenticated/onboarding/caregiver': typeof AuthenticatedOnboardingCaregiverRoute
  '/_authenticated/onboarding/family': typeof AuthenticatedOnboardingFamilyRoute
  '/_authenticated/caregiver/': typeof AuthenticatedCaregiverIndexRoute
  '/_authenticated/family/': typeof AuthenticatedFamilyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/role'
    | '/assistant'
    | '/care-plan'
    | '/shared'
    | '/caregiver/profile'
    | '/family/matches'
    | '/family/profile'
    | '/family/request'
    | '/onboarding/caregiver'
    | '/onboarding/family'
    | '/caregiver/'
    | '/family/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/role'
    | '/assistant'
    | '/care-plan'
    | '/shared'
    | '/caregiver/profile'
    | '/family/matches'
    | '/family/profile'
    | '/family/request'
    | '/onboarding/caregiver'
    | '/onboarding/family'
    | '/caregiver'
    | '/family'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/role'
    | '/_authenticated/assistant'
    | '/_authenticated/care-plan'
    | '/_authenticated/shared'
    | '/_authenticated/caregiver/profile'
    | '/_authenticated/family/matches'
    | '/_authenticated/family/profile'
    | '/_authenticated/family/request'
    | '/_authenticated/onboarding/caregiver'
    | '/_authenticated/onboarding/family'
    | '/_authenticated/caregiver/'
    | '/_authenticated/family/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RoleRoute: typeof RoleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role': {
      id: '/role'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof RoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/care-plan': {
      id: '/_authenticated/care-plan'
      path: '/care-plan'
      fullPath: '/care-plan'
      preLoaderRoute: typeof AuthenticatedCarePlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shared': {
      id: '/_authenticated/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof AuthenticatedSharedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caregiver/': {
      id: '/_authenticated/caregiver/'
      path: '/caregiver'
      fullPath: '/caregiver/'
      preLoaderRoute: typeof AuthenticatedCaregiverIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caregiver/profile': {
      id: '/_authenticated/caregiver/profile'
      path: '/caregiver/profile'
      fullPath: '/caregiver/profile'
      preLoaderRoute: typeof AuthenticatedCaregiverProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/family/': {
      id: '/_authenticated/family/'
      path: '/family'
      fullPath: '/family/'
      preLoaderRoute: typeof AuthenticatedFamilyIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/family/matches': {
      id: '/_authenticated/family/matches'
      path: '/family/matches'
      fullPath: '/family/matches'
      preLoaderRoute: typeof AuthenticatedFamilyMatchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/family/profile': {
      id: '/_authenticated/family/profile'
      path: '/family/profile'
      fullPath: '/family/profile'
      preLoaderRoute: typeof AuthenticatedFamilyProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/family/request': {
      id: '/_authenticated/family/request'
      path: '/family/request'
      fullPath: '/family/request'
      preLoaderRoute: typeof AuthenticatedFamilyRequestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/caregiver': {
      id: '/_authenticated/onboarding/caregiver'
      path: '/onboarding/caregiver'
      fullPath: '/onboarding/caregiver'
      preLoaderRoute: typeof AuthenticatedOnboardingCaregiverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/family': {
      id: '/_authenticated/onboarding/family'
      path: '/onboarding/family'
      fullPath: '/onboarding/family'
      preLoaderRoute: typeof AuthenticatedOnboardingFamilyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedCarePlanRoute: typeof AuthenticatedCarePlanRoute
  AuthenticatedSharedRoute: typeof AuthenticatedSharedRoute
  AuthenticatedCaregiverProfileRoute: typeof AuthenticatedCaregiverProfileRoute
  AuthenticatedFamilyMatchesRoute: typeof AuthenticatedFamilyMatchesRoute
  AuthenticatedFamilyProfileRoute: typeof AuthenticatedFamilyProfileRoute
  AuthenticatedFamilyRequestRoute: typeof AuthenticatedFamilyRequestRoute
  AuthenticatedOnboardingCaregiverRoute: typeof AuthenticatedOnboardingCaregiverRoute
  AuthenticatedOnboardingFamilyRoute: typeof AuthenticatedOnboardingFamilyRoute
  AuthenticatedCaregiverIndexRoute: typeof AuthenticatedCaregiverIndexRoute
  AuthenticatedFamilyIndexRoute: typeof AuthenticatedFamilyIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedCarePlanRoute: AuthenticatedCarePlanRoute,
  AuthenticatedSharedRoute: AuthenticatedSharedRoute,
  AuthenticatedCaregiverProfileRoute: AuthenticatedCaregiverProfileRoute,
  AuthenticatedFamilyMatchesRoute: AuthenticatedFamilyMatchesRoute,
  AuthenticatedFamilyProfileRoute: AuthenticatedFamilyProfileRoute,
  AuthenticatedFamilyRequestRoute: AuthenticatedFamilyRequestRoute,
  AuthenticatedOnboardingCaregiverRoute: AuthenticatedOnboardingCaregiverRoute,
  AuthenticatedOnboardingFamilyRoute: AuthenticatedOnboardingFamilyRoute,
  AuthenticatedCaregiverIndexRoute: AuthenticatedCaregiverIndexRoute,
  AuthenticatedFamilyIndexRoute: AuthenticatedFamilyIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RoleRoute: RoleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
